$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: sentiment-deployment
endpoint_name: chatbot-service-endpoint
model: azureml:custom-sentiment-model:1
instance_type: Standard_DS2_v2
instance_count: 1